In [1]:
import numpy as np

In [2]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[1]

array([4, 5, 6])

in 2d array axis=0 means row and axis=1 means coloumn 

in 1d array axis=1 means row 
and in 3d array axis=0 means depth, axis=1 means rows and axis=2 means coloumn 

In [7]:
print(np.sum(arr,axis=0))#1+4+7
print(np.sum(arr,axis=1))#1+2+3

[12 15 18]
[ 6 15 24]


indexing in multidimensional array

In [11]:
print(arr[1,2])#1 means 2nd row 2 means 3rd coloumn

6


In [12]:
arr[0,2]

np.int64(3)

another way of indexing 

In [13]:
arr[1][1]

np.int64(5)

In [16]:
arr[0:2,0:2]#it will not include the last index so we can say it contains like- [0,2)

array([[1, 2],
       [4, 5]])

typecasting

In [19]:
a1=np.array([1,2,34,64,7])


In [20]:
a1.dtype

dtype('int64')

In [23]:
a2=a1.astype('float64')

In [24]:
a2.dtype

dtype('float64')

In [25]:
a2

array([ 1.,  2., 34., 64.,  7.])

In [29]:
a2.nbytes#storage its taking 

40

In [30]:
arr.nbytes#storage its taking 

72

complex numbers 

In [33]:
ar=np.array([1+2j,3+4j,6+34j], dtype='complex128')


In [34]:
ar

array([1. +2.j, 3. +4.j, 6.+34.j])

Numpy Brodcasting

vectorized operation(vector is faster)

In [35]:
a=np.array([12,3,4,6])
result=a**2

In [36]:
result

array([144,   9,  16,  36])

In [37]:
result=a*2

In [38]:
result

array([24,  6,  8, 12])

In [39]:
result+10

array([34, 16, 18, 22])

brodacsting a 2d array and 1d array

In [44]:
b1=np.array([[1,2,3],[4,5,6]])
b2=np.array([3,7,9])
result= b1+b2
print(result)

[[ 4  9 12]
 [ 7 12 15]]


In [45]:
result2=b2+b1
print(result2)

[[ 4  9 12]
 [ 7 12 15]]


Normalization = (data-mean)/standard deviation

In [47]:
data=np.array([[10,15,20],
               [15,35,30],
               [40,25,45],
               [50,55,15]])
mean=data.mean(axis=0)
std_deviation=data.std(axis=0)
normalized=(data-mean)/std_deviation
print("normalized= ",normalized)

normalized=  [[-1.12115264 -1.18321596 -0.65465367]
 [-0.8221786   0.16903085  0.21821789]
 [ 0.67269158 -0.50709255  1.52752523]
 [ 1.27063966  1.52127766 -1.09108945]]
