In [1]:
import numpy as np

In [4]:
data=np.array([[10,15,20],
               [15,35,30],
               [40,25,45],
               [50,55,15]])
mean=data.mean(axis=0)
std_deviation=data.std(axis=0)
print("mean=" ,mean)

print("standerd deviation= ",std_deviation)
normalized=(data-mean)/std_deviation
print("normalized= ",normalized)

mean= [28.75 32.5  27.5 ]
standerd deviation=  [16.7238602  14.79019946 11.45643924]
normalized=  [[-1.12115264 -1.18321596 -0.65465367]
 [-0.8221786   0.16903085  0.21821789]
 [ 0.67269158 -0.50709255  1.52752523]
 [ 1.27063966  1.52127766 -1.09108945]]
